services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sistemakontrol}
      POSTGRES_USER: ${POSTGRES_USER:-sistemakontrol}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sistemakontrol}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG:-0}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-change-me}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1}
      DJANGO_TIME_ZONE: ${DJANGO_TIME_ZONE:-Europe/Moscow}

      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-sistemakontrol}
      POSTGRES_USER: ${POSTGRES_USER:-sistemakontrol}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sistemakontrol}
      POSTGRES_CONN_MAX_AGE: 60
    ports:
      - "8000:8000"
    volumes:
      - media:/app/media
      - logs:/app/logs

volumes:
  pgdata:
  media:
  logs:
